import Header from "@/components/common/header";
import Footer from "@/components/common/footer";

const Terms = () => {
  return (
    <div className="min-h-screen pt-12 bg-[#0D0C11] text-white font-['Figtree',sans-serif]">
      <Header />
      <div className="max-w-4xl mx-auto px-6 py-24">
        <h1 className="text-4xl font-black mb-8 font-['Satoshi',sans-serif]">Terms of Service</h1>
        <p className="text-gray-400 mb-8 italic">Last Updated: February 11, 2026</p>

        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">1. Acceptance of Terms</h2>
          <p className="text-gray-400 leading-relaxed">
            By accessing or using Zyra, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our services. Zyra provides an AI-powered interface for blockchain interactions and strategy execution.
          </p>
        </section>

        <section className="mb-12 border-l-4 border-blue-500 pl-6 bg-blue-500/5 py-4">
          <h2 className="text-2xl font-bold mb-4 text-blue-400">2. No Ownership of AI Responses</h2>
          <p className="text-gray-300 leading-relaxed font-medium">
            Zyra utilizes Large Language Models (LLMs) to provide suggestions, strategies, and blockchain interaction data. You acknowledge and agree that:
          </p>
          <ul className="list-disc list-inside text-gray-400 mt-4 space-y-2 ml-4">
            <li>Zyra does not take ownership of the content generated by the LLM.</li>
            <li>AI-generated responses are suggestions and do not constitute financial, investment, or legal advice.</li>
            <li>The final decision to execute any transaction or strategy suggested by the AI rests solely with the user.</li>
            <li>Users are responsible for verifying all transaction details, contract addresses, and parameters before signing any transaction on the blockchain.</li>
          </ul>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">3. Cryptocurrency Risks</h2>
          <p className="text-gray-400 leading-relaxed mb-4">
            Blockchain interactions carry inherent risks, including but not limited to:
          </p>
          <ul className="list-disc list-inside text-gray-400 space-y-2 ml-4">
            <li>Volatility: Crypto assets can experience extreme price fluctuations.</li>
            <li>Smart Contract Risk: Underlying protocols may have vulnerabilities or bugs.</li>
            <li>Permanence: Blockchain transactions are irreversible. Once executed, funds cannot be recovered.</li>
            <li>Regulatory Risk: Changes in laws or regulations may affect the legality or functionality of certain services.</li>
          </ul>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">4. User Responsibility</h2>
          <p className="text-gray-400 leading-relaxed">
            You are responsible for maintaining the security of your wallet and private keys. Zyra never stores your private keys or seed phrases. Any loss of funds due to compromised credentials or user-initiated transactions is not the responsibility of Zyra.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">5. Limitation of Liability</h2>
          <p className="text-gray-400 leading-relaxed">
            To the maximum extent permitted by law, Zyra and its team shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits or revenues, whether incurred directly or indirectly, or any loss of data, use, goodwill, or other intangible losses resulting from your use of the service.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-4">6. Modification of Terms</h2>
          <p className="text-gray-400 leading-relaxed">
            We reserve the right to modify these terms at any time. We will notify users of any changes by posting the new terms on this page and updating the "Last Updated" date.
          </p>
        </section>
      </div>
      <Footer />
    </div>
  );
};

export default Terms;
