import { useState } from "react";
import { X, Plus } from "lucide-react";

const FAQ = () => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const faqs = [
    {
      question: "What is USDs, and how is it different from other stablecoins?",
      answer:
        "Sperax is a decentralized finance (DeFi) company specializing in yield-aggregator protocols. Our flagship product is USDs, a stablecoin yield aggregator on the Arbitrum network that blends collateral-backed security with efficiency. As we continue improving DeFi solutions, we are also developing an upcoming yield optimizer designed to maximize users' returns while maintaining risk transparency. Our work is audited by leading firms such as Certik, Quantstamp, PeckShield, and Slowmist to ensure the highest standards related to security and reliability.",
    },
    {
      question: "How is USDs yield generated?",
      answer:
        "USDs generates yield through a combination of collateral management and strategic DeFi integrations. The protocol automatically allocates assets to the most profitable opportunities while maintaining stability.",
    },
    {
      question: "What happens to the yield generated by USDs collateral?",
      answer:
        "The yield generated by USDs collateral is automatically distributed to USDs holders. A portion is used to maintain the protocol's stability, while the rest is passed on to users.",
    },
    {
      question: "Are there any fees associated with the auto-yield feature?",
      answer:
        "There are minimal fees associated with the auto-yield feature to cover gas costs and protocol maintenance. All fees are transparently displayed before any transaction.",
    },
  ];

  const toggleFAQ = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="bg-[#0D0C11] flex flex-col gap-[64px] items-center justify-center py-[84px] w-full max-w-[1440px] mx-auto">
      {/* Header */}
      <div className="flex flex-col gap-[16px] items-start text-center w-full">
        <p className="bg-clip-text font-['Figtree',sans-serif] font-semibold text-[48px] leading-[54px] tracking-[-0.96px] text-transparent bg-gradient-to-r from-white to-[#7CABF9] w-full">
          We got your <span className="text-[#3B82F6]">answer</span>
        </p>
        <p className="font-['Figtree',sans-serif] font-normal text-[16px] leading-[24px] text-white w-full">
          Everything you might want to know before we work together answered clearly and simply
        </p>
      </div>

      {/* FAQ Items */}
      <div className="flex flex-col gap-[24px] items-start justify-center px-[135px] w-full">
        {faqs.map((faq, index) => (
          <div
            key={index}
            className="border-b border-[rgba(255,255,255,0.08)] border-solid flex flex-col gap-[16px] items-start py-[24px] w-full"
          >
            <button
              onClick={() => toggleFAQ(index)}
              className="flex items-center justify-between w-full"
            >
              <p className="font-['Figtree',sans-serif] font-medium text-[24px] leading-[30px] text-center text-white tracking-[-0.48px] whitespace-pre text-left">
                {faq.question}
              </p>
              <div className="overflow-clip shrink-0 w-[24px] h-[24px]">
                {openIndex === index ? (
                  <X className="w-[24px] h-[24px] text-white" strokeWidth={1.5} />
                ) : (
                  <Plus className="w-[24px] h-[24px] text-white" strokeWidth={1.5} />
                )}
              </div>
            </button>
            <div
              className={`overflow-hidden transition-all duration-300 ${
                openIndex === index ? "max-h-[500px]" : "max-h-0"
              }`}
            >
              <div className="flex gap-[8px] items-center justify-center pr-[84px] w-full">
                <p className="basis-0 font-['Figtree',sans-serif] font-normal grow text-[14px] leading-[20px] opacity-60 text-white min-h-px min-w-px">
                  {faq.answer}
                </p>
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default FAQ;
